name: Omniscience
version: ${project.version}
main: io.github.warhead501.omniscience.Omniscience
softdepend: [WorldEdit, FastAsyncWorldEdit, CraftBook]
authors: [501warhead]
description: The Spigot solution to block logging and rollbacks for 1.13.2+
website: https://github.com/501warhead/Omniscience
api-version: 1.16

commands:
  omniscience:
    aliases: [o, omni]
    usage: /<command> help
    permission: omniscience.mayuse
  omnitele:
    usage: /<command>
    permission: omniscience.mayuse