version: "3.9"
services:
  omniscience-mongodb:
    image: mongo
    container_name: omniscience-mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/data/db
    expose:
      - "27017"
    restart: unless-stopped
networks:
  default:
    external: true
    name: pterodactyl_nw